# This pipeline is used to incorporate security patches into the image
# We cannot rely on changes to the code to include updates to the base image

name: Docker CI Image Updates

# Controls when the action will run. 
on:
  #Every sunday
  schedule:
    - cron: '0 4 * * 6'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Get the tags and history
      run: git fetch --prune --unshallow

    - name: Set env
      run: echo "RELEASE_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      
    - name: Test
      run: echo $RELEASE_VERSION

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qbittorrent:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/qbittorrent:${{ env.RELEASE_VERSION }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

