name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '39 10 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Bot: Closing the issue due to inactivity.'
        stale-pr-message: 'Bot: Closing the pull request due to inactivity.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
